# https://github.com/devcontainers/images/blob/84a5cfc254a7965a74907aaa269d4409fbb07f37/src/go/history/2.0.3.md#variant-125-trixie
FROM mcr.microsoft.com/devcontainers/go:1.25-trixie

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment the next lines to use go get to install anything else you need
# USER vscode
# RUN go get -x <your-dependency-or-tool>
# USER root

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
